# Copyright 2015-2016 Tim Kouters (Falcons)
# SPDX-License-Identifier: Apache-2.0
    
class WorldModelInterfaces:
    S_GET_TEAMMEMBERS = "s_get_teammembers"
    S_GET_OWN_LOCATION = "s_get_own_location"
    S_GET_OPPONENTS = "s_get_opponents"
    S_GET_OWN_OBSTACLES = "s_get_own_obstacles"
    S_SET_OWN_LOCATION = "s_set_own_location"
    S_SET_MEMBER_LOCATION = "s_set_member_location"
    S_SET_OWN_OBSTACLE_LOCATION = "s_set_own_obstacle_location"
    S_SET_REMOTE_OBSTABLE_LOCATION = "s_set_remote_obstacle_location"
    S_SET_OWN_BALL_LOCATION = "s_set_own_ball_location"
    S_SET_OWN_FRONT_CAMERA_BALL_LOCATION = "s_set_own_front_camera_ball_location"
    S_SET_REMOTE_BALL_LOCATION = "s_set_remote_ball_location"
    S_GET_BALL_POSSESSION = "s_get_ball_possession"
    S_SET_REMOTE_BALL_POSSESSION = "s_set_remote_ball_possession"
    S_GET_BALL_LOCATION = "s_get_ball_location"
    S_GET_OWN_BALL_LOCATION = "s_get_own_ball_location"
    S_CLAIM_BALL_POSSESSION = "s_claim_ball_possession"
    S_RELEASE_BALL_POSSESSION = "s_release_ball_possession"
    S_GET_ACTIVE_ROBOTS = "s_get_active_robots"
    S_SET_OWN_ENCODER_DISPLACEMENT = "s_set_own_encoder_displacement"
    S_SET_OWN_ROBOT_STATUS = "s_set_own_robot_status"
    S_GET_LAST_KNOWN_BALL_LOCATION = "s_get_last_known_ball_location"
    S_FORCE_RECALCULATION = "s_force_recalculation"