#!/bin/bash -e

if [ ! -f /usr/local/lib/libdarknet.so ]; then
   echo "ERROR: install libdarknet.so"
   exit 1
fi

if [ ! -f /usr/local/include/darknet.h ]; then
   echo "ERROR: install darknet.h"
   exit 1
fi

mkdir -p build

# qmake should be in your path, e.g. 
# PATH=$PATH:/opt/Qt5.14.2/5.14.2/gcc_64/bin/
qmake -o build/Makefile jpgToDarknet.pro

cd build

make -j 8 

cd ../

./build/jpgToDarknet


exit 0

make -j 8 \
  detector.o \
  fileReader.o \
  imageTools.o \
  main.o \
  mjpgSender.o \
  receiver.o \
  widget.o \
  moc_mjpgSender.o \
  moc_receiver.o \
  moc_widget.o

#  -Wl,-Bstatic \
#  -Wl,-Bdynamic \


g++ -O3 -DNDEBUG -rdynamic \
  -L/usr/local/lib \
   detector.o fileReader.o imageTools.o main.o mjpgSender.o receiver.o widget.o moc_mjpgSender.o moc_receiver.o moc_widget.o \
  -o jpgToDarknet \
  -Wl,-rpath,/opt/Qt5.14.2/5.14.2/gcc_64/lib \
  -Wl,-rpath,/usr/local/lib \
  -ldarknet \
  /opt/Qt5.14.2/5.14.2/gcc_64/lib/libQt5Widgets.so \
  /opt/Qt5.14.2/5.14.2/gcc_64/lib/libQt5Gui.so \
  /opt/Qt5.14.2/5.14.2/gcc_64/lib/libQt5Network.so \
  /opt/Qt5.14.2/5.14.2/gcc_64/lib/libQt5Core.so \
  -lGL

cd ../

./build/jpgToDarknet

