#!/bin/bash
#
# Regression test sequence.
#
# First run unit tests,
# then run system tests.


cd "$(dirname "$0")"
./runtests_unitlevel || exit 1

# system/simulation tests to be implemented
#./runtests_robotframework

