// Copyright 2019-2020 Jan Feitsma (Falcons)
// SPDX-License-Identifier: Apache-2.0
/*
 * treeEnum.hpp
 *
 *  Created on: April 2019
 *      Author: Jan Feitsma
 */

#ifndef TPTREEENUM_HPP_
#define TPTREEENUM_HPP_

#include "RtDB2.h"


enum class treeEnum
{
    INVALID = 0,

    // GAMESTATES
    IN_MATCH_NEUTRAL_STOPPED_NEUTRAL,
    IN_MATCH_NEUTRAL_PLAYING_NEUTRAL,
    IN_MATCH_OWN_KICKOFF_PREPARE_NEUTRAL,
    IN_MATCH_OPP_KICKOFF_PREPARE_NEUTRAL,
    IN_MATCH_OWN_KICKOFF_EXECUTE_NEUTRAL,
    IN_MATCH_OPP_KICKOFF_EXECUTE_NEUTRAL,
    IN_MATCH_OWN_FREEKICK_PREPARE_NEUTRAL,
    IN_MATCH_OPP_FREEKICK_PREPARE_NEUTRAL,
    IN_MATCH_OWN_FREEKICK_EXECUTE_NEUTRAL,
    IN_MATCH_OPP_FREEKICK_EXECUTE_NEUTRAL,
    IN_MATCH_OWN_GOALKICK_PREPARE_NEUTRAL,
    IN_MATCH_OPP_GOALKICK_PREPARE_NEUTRAL,
    IN_MATCH_OWN_GOALKICK_EXECUTE_NEUTRAL,
    IN_MATCH_OPP_GOALKICK_EXECUTE_NEUTRAL,
    IN_MATCH_OWN_THROWIN_PREPARE_NEUTRAL,
    IN_MATCH_OPP_THROWIN_PREPARE_NEUTRAL,
    IN_MATCH_OWN_THROWIN_EXECUTE_NEUTRAL,
    IN_MATCH_OPP_THROWIN_EXECUTE_NEUTRAL,
    IN_MATCH_OWN_CORNER_PREPARE_NEUTRAL,
    IN_MATCH_OPP_CORNER_PREPARE_NEUTRAL,
    IN_MATCH_OWN_CORNER_EXECUTE_NEUTRAL,
    IN_MATCH_OPP_CORNER_EXECUTE_NEUTRAL,
    IN_MATCH_OWN_PENALTY_PREPARE_NEUTRAL,
    IN_MATCH_OPP_PENALTY_PREPARE_NEUTRAL,
    IN_MATCH_OWN_PENALTY_EXECUTE_NEUTRAL,
    IN_MATCH_OPP_PENALTY_EXECUTE_NEUTRAL,
    IN_MATCH_DROPPED_BALL_PREPARE_NEUTRAL,
    IN_MATCH_DROPPED_BALL_EXECUTE_NEUTRAL,

    OUT_OF_MATCH_NEUTRAL_STOPPED_NEUTRAL,
    OUT_OF_MATCH_OWN_PENALTY_PREPARE_NEUTRAL,
    OUT_OF_MATCH_OPP_PENALTY_PREPARE_NEUTRAL,
    OUT_OF_MATCH_OWN_PENALTY_EXECUTE_NEUTRAL,
    OUT_OF_MATCH_OPP_PENALTY_EXECUTE_NEUTRAL,
    PARKING,

    // ROLES
    ATTACKER_MAIN,
    ATTACKER_ASSIST,
    DEFENDER_MAIN,
    DEFENDER_ASSIST,
    R_GOALKEEPER,
    R_ROBOT_STOP,

    // BEHAVIORS
    B_GOALKEEPER,
    B_ROBOT_STOP,
    ATTACKER_PASS_BALL_STRATEGY,
    ATTACKER_PLAY_BALL,
    ATTACK_ASSIST,
    ATTACK_MAIN,
    DEFEND_ASSIST,
    DEFEND_POTENTIAL_OPP_ATTACKER,
    DEFEND_MAIN,
    DEFENDER_PASS_BALL_STRATEGY,
    DEFENDER_PLAY_BALL,
    DROPBALL_EXECUTE,
    DROPBALL_PREPARE,
    DROPBALL_SEARCH,
    GET_BALL,
    OPP_CORNER_PREPARE,
    OPP_CORNER_SEARCH,
    OPP_FREEKICK_PREPARE,
    OPP_FREEKICK_SEARCH,
    OPP_GOALKICK_PREPARE,
    OPP_GOALKICK_SEARCH,
    OPP_KICKOFF_PREPARE,
    OPP_KICKOFF_SEARCH,
    OPP_PENALTY_PREPARE,
    OPP_THROWIN_PREPARE,
    OPP_THROWIN_SEARCH,
    OWN_CORNER_EXECUTE,
    OWN_CORNER_PREPARE,
    OWN_CORNER_SEARCH,
    OWN_FREEKICK_EXECUTE,
    OWN_FREEKICK_PREPARE,
    OWN_FREEKICK_SEARCH,
    OWN_GOALKICK_EXECUTE,
    OWN_GOALKICK_PREPARE,
    OWN_GOALKICK_SEARCH,
    OWN_KICKOFF_EXECUTE,
    OWN_KICKOFF_PREPARE,
    OWN_KICKOFF_SEARCH,
    OWN_PENALTY_EXECUTE,
    OWN_PENALTY_PREPARE,
    OWN_THROWIN_EXECUTE,
    OWN_THROWIN_PREPARE,
    OWN_THROWIN_SEARCH,
    PASS_BALL_TO_CLOSEST_ATTACKER,
    PASS_BALL_TO_FURTHEST_ATTACKER,
    PASS_BALL_TO_FURTHEST_DEFENDER,
    PASS_BALL_TO_CLOSEST_TEAMMEMBER,
    PASS_BALL_TO_CLOSEST_ATTACKER_ON_OPP_HALF,
    POSITION_TO_FREE_SPOT,
    POSITION_TO_SHOOT,
    POSITION_TO_PASS,
    RECEIVE_PASS,
    SEARCH_BALL,
    SETPIECE,
    SETPIECE_SEARCH_BALL,
    SHOOT_AT_GOAL,
    LOB_SHOT_ON_GOAL,
    TIP_IN_ASSIST,
    TIP_IN_EXECUTE,
    TURN_AWAY_FROM_CLOSEST_OPPONENT,
    TEST_OBSTACLE_STRAFE,
    PARK,

    SIZE_OF_ENUM
};

SERIALIZE_ENUM(treeEnum);

#endif

