ballhandlerPlotEnabled  : False     # Enable Data Dump for plotting
Kp                      : 2500      # BallHandler P-value of PID (max=65536)
Ki                      : 0         # BallHandler I-value of PID (max=65536)
Kd                      : 0         # BallHandler D-value of PID (max=65536)
iTh                     : 0         # Threshold of using I (iMin) -- (max=65536)
iMax                    : 0         # Limits the maximum I value (max=100000)
Ang_Kp                  : 5000      # BallHandler Angle P-value of PID (max=65536)
Ang_Ki                  : 0         # BallHandler Angle I-value of PID (max=65536)
Ang_Kd                  : 0         # BallHandler Angle D-value of PID (max=65536)
PwmMax                  : 600       # PWM Maximum power (max=648)
PwmMaxDeltaSize         : 200000    # PWM maximum step size per cycle (2.5ms, 400Hz, max=648<<16)
