BallHandlingNode: {
  AngleSetpoint: 0.8,
  BallPossessionAngleThresholdOff: 0.2,
  BallPossessionAngleThresholdOn: 0.6,
  ArmLiftedAngleThreshold: 0.4,
  BallPossessionTimeInterval: 300,

  EnableRobotVelocityFeedForward: True,
  DisableRobotVelocityFeedForwardWhenNoBallPossession: True,
  XFeedForwardVelocityFactor: 10.0,
  YFeedForwardVelocityFactor: -10.0,
  ThetaFeedForwardVelocityFactor: 4.0,

  EnableExtraPullForceWhenSingleArmUp: True,
  DisableExtraPullForceWhenBallPossession: True,
  ExtraPullForceVelocity: 60.0
} 
rosdistro: 'groovy

  '
roslaunch:
  uris: {host_localhost__52278: 'http://localhost:52278/', host_localhost__32819: 'http://localhost:32819/'}
rosversion: '1.9.55

  '
run_id: d837e3c8-6813-11e4-acf7-00197e8a14ee

