frequency:                     20.0      # [Hz]     change to 30 if needed
simulationSpeedupFactor:        1.0      # [double] The speedup factor for simulation, e.g., 2.0 -> simulation time advances at 200%: 1 real-world second == 2 seconds in simulation time
tickFinishRtdbKey:          "ACTION_RESULT"    # [string] The RtDB key that is written when a tick / heartbeat finishes. Execution will subscribe to this RtDB key.
