getBallConfig:
    obstacleThreshold:      3.0
    ballSpeedThreshold:     0.35
    ballSpeedScaling:       0.6
interceptBallConfig:
    obstacleThreshold:      3.0
    ballSpeedThreshold:     0.35
    ballSpeedScaling:       0.6
    captureRadius:          2.1
    activeIntercept:        False
keeperMoveConfig:
    yMaxOffset:             0.3   # distance "out of the goal"
    xGoalpostOffset:        0.45  # distance from the goalpost (sideways/X direction)
passToTargetConfig:
    aimSettleTime:          0.2
    accuracy:               0.05  # keep trying, optimize for short pass
    timeout:                1.0
    coarseAngle:            0.5
    disableBhDelay:         0.1   # for (short) passes, if tuned agressively, ballHandling will cause either small bump or reduce pass power
    sleepAfterShoot:        0.3
shootAtTargetConfig:
    aimSettleTime:          0.1
    accuracy:               0.2
    timeout:                0.6
    coarseAngle:            0.5
    disableBhDelay:         0.0
    sleepAfterShoot:        0.3
