peripheralsInterface/motors: {
    Kp : 8000,
    Ki : 2000,
    Kd : 0,
    iTh : 5,
    iMax : 3283,
    PwmMax : 500,
    PwmMaxDeltaSize : 147704
} 
rosdistro: 'groovy'
roslaunch:
    uris: {host_localhost__52279: 'http://localhost:52278/', host_localhost__32819: 'http://localhost:32819/'}
rosversion: '1.9.55'
run_id: d837e3c8-6813-11e4-acf7-00197e8a14ee
