nominalFrequency:                         30
numExtraSettlingTicks:                    0
obstacleAvoidance:
    enabled:                              true
    robotRadius:                          0.26
    obstacleRadius:                       0.40
    distanceScalingFactor:                0.1
    speedScalingFactor:                   0.5
    speedLowerThreshold:                  0.2
    speedUpperThreshold:                  3.0
    ballClearance:                        1.0
    generatedObstacleSpacing:             0.5
    groupGapDistance:                     0.60
    subTargetDistance:                    0.75
    subTargetExtensionFactor:             0.0
boundaries:
    targetInsideForbiddenArea:            BoundaryOptionEnum:STOP_AND_FAIL
    targetOutsideField:                   BoundaryOptionEnum:CLIP
    fieldMarginX:                         1.0
    fieldMarginY:                         0.5
    targetOnOwnHalf:                      BoundaryOptionEnum:ALLOW
    targetOnOpponentHalf:                 BoundaryOptionEnum:ALLOW
slowFactor:                               0.50
forwardDriving:
    withoutBall:
        enabled:                          false # set to false to get 'alwaysFacingBall' Rz setpoint
        minimumDistance:                  1.0
    withBall:
        enabled:                          true
        minimumDistance:                  1.0
    radiusRobotToBall:                    0.26
    applyLimitsToBall:                    true # generalization of Tokyo Drift
deadzone:
    enabled:                              true # true = better for motors (not continuously sending small setpoints)
    toleranceXY:                          0.02
    toleranceRz:                          0.005 # real Rz-only performance is a bit worse (~0.012) due to wheel mounting errors (wobbly, at least seen on r5)