nominalFrequency:                         20
numExtraSettlingTicks:                    1
obstacleAvoidance:
    enabled:                              true
    robotRadius:                          0.26
    obstacleRadius:                       0.26
    distanceScalingFactor:                0.0
    speedScalingFactor:                   1.0
    speedLowerThreshold:                  0.2
    speedUpperThreshold:                  3.0
    ballClearance:                        1.0
    generatedObstacleSpacing:             0.5
    groupGapDistance:                     0.60
    subTargetDistance:                    0.75
    subTargetExtensionFactor:             0.0
boundaries:
    targetInsideForbiddenArea:            BoundaryOptionEnum:STOP_AND_FAIL
    targetOutsideField:                   BoundaryOptionEnum:ALLOW
    fieldMarginX:                         1.0
    fieldMarginY:                         0.5
    targetOnOwnHalf:                      BoundaryOptionEnum:ALLOW
    targetOnOpponentHalf:                 BoundaryOptionEnum:ALLOW
slowFactor:                               0.50
forwardDriving:
    withoutBall:
        enabled:                          true # maximize speed
        minimumDistance:                  1.5
    withBall:
        enabled:                          true
        minimumDistance:                  0.9
    radiusRobotToBall:                    0.26
    applyLimitsToBall:                    false # false: simulate perfect ballHandling; true: probably more realistic
deadzone:
    enabled:                              false
    toleranceXY:                          0.01
    toleranceRz:                          0.001
