numExtraSettlingTicks:                    0
obstacleAvoidance:
    enabled:                              true # keeperMove will overrule to disable in goal area
    robotRadius:                          0.40 # extra margin for keeper frame
    obstacleRadius:                       0.40
    distanceScalingFactor:                0.1
    speedScalingFactor:                   0.5
    speedLowerThreshold:                  0.2
    speedUpperThreshold:                  3.0
    ballClearance:                        1.0
    generatedObstacleSpacing:             0.5
    groupGapDistance:                     0.60
    subTargetDistance:                    0.75
    subTargetExtensionFactor:             0.0
boundaries:
    targetInsideForbiddenArea:            BoundaryOptionEnum:STOP_AND_FAIL
    targetOutsideField:                   BoundaryOptionEnum:CLIP
    fieldMarginX:                         1.0
    fieldMarginY:                         0.5
    targetOnOwnHalf:                      BoundaryOptionEnum:ALLOW
    targetOnOpponentHalf:                 BoundaryOptionEnum:ALLOW
slowFactor:                               0.50
forwardDriving:
    withoutBall:
        enabled:                          false
        minimumDistance:                  2.0
    withBall:
        enabled:                          false
        minimumDistance:                  2.0
    radiusRobotToBall:                    0.26
    applyLimitsToBall:                    true
deadzone:
    enabled:                              true # true = better for motors (not continuously sending small setpoints)
    toleranceXY:                          0.02
    toleranceRz:                          0.002
tokyoDrift:
    toleranceRz:                          1.0 # if deltaPos.Rz > tokyoDrift.toleranceRz -> do tokyo drift; otherwise do normal rotation
