PathPlanningNode: {
  Obstacle_avoidance_enabled                       :   False,

  normal_Limiters_maxVelXY                         :   1.50,
  normal_Limiters_maxVelXY_withBall                :   0.50,
  normal_Limiters_maxVelPhi                        :   2.00,
  normal_Limiters_maxVelPhi_withBall               :   1.00,
  normal_Limiters_maxAccXY                         :   4.5,
  normal_Limiters_maxAccPhi                        :   7.0,
  normal_Limiters_tolerationXY                     :   0.03,
  normal_Limiters_tolerationPhi                    :   0.01,
  normal_Limiters_relativeSpeedFactorX             :   1.0,
  normal_Limiters_relativeSpeedFactorY             :   1.0,
  normal_Limiters_relativeSpeedFactorPhi           :   1.0,
  normal_Limiters_obstacleAvoidanceScalingFactor   :   0.1,
  normal_Limiters_obstacleAvoidanceDistanceFactor  :   1.0,
  normal_Linear_gainXY                             :   1.0,
  normal_Linear_gainPhi                            :   1.0,
  normal_PFMalgo_dist_lim                          :   4.00,
  normal_PFMalgo_force_max                         :   5.00,
  normal_PFMalgo_force_min                         :   0.01,
  normal_PFMalgo_expo_rep                          :   2.50,
  normal_PFMalgo_mult_rep                          :  19.0,
  normal_PFMalgo_gain_rep                          :   3.00,
  normal_PFMalgo_gain_attr                         :  15.00,
  normal_PIDalgo_X_P                               :   4.0,
  normal_PIDalgo_X_I                               :  20.0,
  normal_PIDalgo_X_D                               :   8.0,
  normal_PIDalgo_Y_P                               :   4.0,
  normal_PIDalgo_Y_I                               :  20.0,
  normal_PIDalgo_Y_D                               :   8.0,
  normal_PIDalgo_XY_P                              :   5.0,
  normal_PIDalgo_XY_I                              :   0.01,
  normal_PIDalgo_XY_D                              :   1.0,
  normal_PIDalgo_PHI_P                             :   1.0,
  normal_PIDalgo_PHI_I                             :   0.01,
  normal_PIDalgo_PHI_D                             :   0.5,
  normal_PIDalgo_maxI_XY                           :   0.5,
  normal_PIDalgo_maxI_Phi                          :   0.1,
  normal_Brake_deceleration                        :   0.0,
  normal_Brake_gamma                               :   0.0,
  normal_TokyoDrift_radius                         :   0.25,
  normal_TokyoDrift_step_angle                     :   0.785,
  normal_TokyoDrift_facing_target_tol              :   0.5,

  setpiece_Limiters_maxVelXY                         :   0.50,
  setpiece_Limiters_maxVelXY_withBall                :   0.50,
  setpiece_Limiters_maxVelPhi                        :   2.00,
  setpiece_Limiters_maxVelPhi_withBall               :   1.80,
  setpiece_Limiters_maxAccXY                         :   1.0,
  setpiece_Limiters_maxAccPhi                        :   4.0,
  setpiece_Limiters_tolerationXY                     :   0.05,
  setpiece_Limiters_tolerationPhi                    :   0.005,
  setpiece_Limiters_relativeSpeedFactorX             :   1.0,
  setpiece_Limiters_relativeSpeedFactorY             :   1.0,
  setpiece_Limiters_relativeSpeedFactorPhi           :   1.0,
  setpiece_Limiters_obstacleAvoidanceScalingFactor   :   0.5,
  setpiece_Limiters_obstacleAvoidanceDistanceFactor  :   1.0,
  setpiece_Linear_gainXY                             :   1.0,
  setpiece_Linear_gainPhi                            :   1.0,
  setpiece_PFMalgo_dist_lim                          :   4.00,
  setpiece_PFMalgo_force_max                         :   5.00,
  setpiece_PFMalgo_force_min                         :   0.01,
  setpiece_PFMalgo_expo_rep                          :   2.50,
  setpiece_PFMalgo_mult_rep                          :  19.0,
  setpiece_PFMalgo_gain_rep                          :   3.00,
  setpiece_PFMalgo_gain_attr                         :  15.00,
  setpiece_PIDalgo_X_P                               :   4.0,
  setpiece_PIDalgo_X_I                               :  20.0,
  setpiece_PIDalgo_X_D                               :   8.0,
  setpiece_PIDalgo_Y_P                               :   4.0,
  setpiece_PIDalgo_Y_I                               :  20.0,
  setpiece_PIDalgo_Y_D                               :   8.0,
  setpiece_PIDalgo_XY_P                              :   2.0,
  setpiece_PIDalgo_XY_I                              :   0.01,
  setpiece_PIDalgo_XY_D                              :   0.0,
  setpiece_PIDalgo_PHI_P                             :   1.0,
  setpiece_PIDalgo_PHI_I                             :   0.5,
  setpiece_PIDalgo_PHI_D                             :   0.0,
  setpiece_PIDalgo_maxI_XY                           :   0.5,
  setpiece_PIDalgo_maxI_Phi                          :   0.5,
  setpiece_Brake_deceleration                        :   0.0,
  setpiece_Brake_gamma                               :   0.0,
  setpiece_TokyoDrift_radius                         :   0.25,
  setpiece_TokyoDrift_step_angle                     :   0.785,
  setpiece_TokyoDrift_facing_target_tol              :   0.5,
}
rosdistro: 'groovy

  '
roslaunch:
  uris: {host_localhost__52278: 'http://localhost:52278/', host_localhost__32819: 'http://localhost:32819/'}
rosversion: '1.9.55

  '
run_id: d837e3c8-6813-11e4-acf7-00197e8a14ee
