nominalFrequency:                         30
numExtraSettlingTicks:                    0
velocityControllers:
    threshold:                            1.0
    longStroke:
        type:                             VelocitySetpointControllerTypeEnum:SPG
        coordinateSystem:                 CoordinateSystemEnum:RCS
    shortStroke:
        type:                             VelocitySetpointControllerTypeEnum:PID
        coordinateSystem:                 CoordinateSystemEnum:FCS
obstacleAvoidance:
    enabled:                              true # keeperMove will overrule to disable in goal area
    robotRadius:                          0.40 # extra margin for keeper frame
    obstacleRadius:                       0.40
    distanceScalingFactor:                0.1
    speedScalingFactor:                   0.5
    speedLowerThreshold:                  0.2
    speedUpperThreshold:                  3.0
    ballClearance:                        1.0
    generatedObstacleSpacing:             0.5
    groupGapDistance:                     0.60
    subTargetDistance:                    0.75
    subTargetExtensionFactor:             0.0
boundaries:
    targetInsideForbiddenArea:            BoundaryOptionEnum:STOP_AND_FAIL
    targetOutsideField:                   BoundaryOptionEnum:CLIP
    fieldMarginX:                         1.0
    fieldMarginY:                         0.5
    targetOnOwnHalf:                      BoundaryOptionEnum:ALLOW
    targetOnOpponentHalf:                 BoundaryOptionEnum:ALLOW
slowFactor:                               0.50
forwardDriving:
    withoutBall:
        enabled:                          false
        minimumDistance:                  2.0
    withBall:
        enabled:                          false
        minimumDistance:                  2.0
    radiusRobotToBall:                    0.26
    applyLimitsToBall:                    true
limits:
    enabled:                              true
    withoutBall:
        maxVelX:                          2.0 # main movement direction
        maxVelYforward:                   1.0 # slow drive for park
        maxVelYbackward:                  1.0
        maxVelRz:                         1.0
        maxAccX:                          4.5 # aggressive
        maxAccYforward:                   1.5
        maxAccYbackward:                  1.5
        maxAccRz:                         3.0
    withBall:
        maxVelX:                          0.0 # keeper cannot hold ball
        maxVelYforward:                   0.0
        maxVelYbackward:                  0.0
        maxVelRz:                         0.0
        maxAccX:                          0.0
        maxAccYforward:                   0.0
        maxAccYbackward:                  0.0
        maxAccRz:                         0.0
    common:
        maxDecX:                          4.0
        maxDecY:                          7.0
        maxDecRz:                         5.0
        toleranceXY:                      0.02
        toleranceRz:                      0.002
        accThresholdX:                    0.0
        accThresholdY:                    0.0
        accThresholdRz:                   0.0
deadzone:                                 true
setPointGenerator:
    synchronizeRotation:                  false
    weightFactorClosedLoop:               0.0
    latencyOffset:                        0.0
    convergenceWorkaround:                false
pid:
    XY_P:                                 3.0
    XY_I:                                 0.01
    XY_D:                                 0.1
    RZ_P:                                 1.0
    RZ_I:                                 0.1
    RZ_D:                                 0.5
    maxI_XY:                              0.5
    maxI_Rz:                              0.1
    fadeI_XY:                             1.00
    fadeI_Rz:                             0.99

