obstacleAvoidanceEnabled:                 true
normal:
    limiters:
        maxVelXY:                         1.80
        maxVelXY_withBall:                1.20
        maxVelPhi:                        2.30
        maxVelPhi_withBall:               4.00
        maxAccXY:                         1.60
        maxAccPhi:                       15.00
        tolerationXY:                     0.02
        tolerationPhi:                    0.002
        relativeSpeedFactorX:             1.0
        relativeSpeedFactorY:             1.0
        relativeSpeedFactorPhi:           1.0
        obstacleAvoidanceScalingFactor:   0.5
        obstacleAvoidanceDistanceFactor:  1.0
    pid:
        X_P:                              4.0
        X_I:                             20.0
        X_D:                              8.0
        Y_P:                              4.0
        Y_I:                             20.0
        Y_D:                              8.0
        XY_P:                             1.5
        XY_I:                             0.01
        XY_D:                             0.0
        PHI_P:                            1.5
        PHI_I:                            0.01
        PHI_D:                            0.175
        maxI_XY:                          0.5
        maxI_Phi:                         0.5
    brake_deceleration:                   0.0
    brake_gamma:                          0.0
    tokyoDrift_radius:                    0.25
    tokyoDrift_step_angle:                0.785
    tokyoDrift_facing_target_tol:         0.5
setpiece:
    limiters:
        maxVelXY:                         0.50
        maxVelXY_withBall:                0.50
        maxVelPhi:                        1.60
        maxVelPhi_withBall:               1.44
        maxAccXY:                         1.00
        maxAccPhi:                        3.20
        tolerationXY:                     0.01
        tolerationPhi:                    0.001
        relativeSpeedFactorX:             1.0
        relativeSpeedFactorY:             1.0
        relativeSpeedFactorPhi:           1.0
        obstacleAvoidanceScalingFactor:   0.5
        obstacleAvoidanceDistanceFactor:  1.0
    pid:
        X_P:                              4.0
        X_I:                             20.0
        X_D:                              8.0
        Y_P:                              4.0
        Y_I:                             20.0
        Y_D:                              8.0
        XY_P:                             2.0
        XY_I:                             0.01
        XY_D:                             0.0
        PHI_P:                            1.0
        PHI_I:                            0.5
        PHI_D:                            0.0
        maxI_XY:                          0.5
        maxI_Phi:                         0.5
    brake_deceleration:                   0.0
    brake_gamma:                          0.0
    tokyoDrift_radius:                    0.25
    tokyoDrift_step_angle:                0.785
    tokyoDrift_facing_target_tol:         0.5

