obstacleAvoidanceEnabled:                 true
normal:
    limiters:
        maxVelXY:                         2.00
        maxVelXY_withBall:                1.50
        maxVelPhi:                        2.00
        maxVelPhi_withBall:               4.00
        maxAccXY:                         3.50
        maxAccPhi:                        3.50
        tolerationXY:                     0.01
        tolerationPhi:                    0.001
        relativeSpeedFactorX:             1.0
        relativeSpeedFactorY:             1.0
        relativeSpeedFactorPhi:           1.0
        obstacleAvoidanceScalingFactor:   0.1
        obstacleAvoidanceDistanceFactor:  1.0
    pid:
        X_P:                              0.9
        X_I:                              0.0
        X_D:                              0.0
        Y_P:                              0.9
        Y_I:                              0.0
        Y_D:                              0.0
        XY_P:                             0.9
        XY_I:                             0.0
        XY_D:                             0.0
        PHI_P:                            0.9
        PHI_I:                            0.0
        PHI_D:                            0.0
        maxI_XY:                          0.5
        maxI_Phi:                         0.1
    brake_deceleration:                   0.0
    brake_gamma:                          0.0
    tokyoDrift_radius:                    0.2
    tokyoDrift_step_angle:                0.785
    tokyoDrift_facing_target_tol:         0.5
setpiece:
    limiters:
        maxVelXY:                         0.50
        maxVelXY_withBall:                1.50
        maxVelPhi:                        2.00
        maxVelPhi_withBall:               1.00
        maxAccXY:                         3.50
        maxAccPhi:                        3.50
        tolerationXY:                     0.01
        tolerationPhi:                    0.001
        relativeSpeedFactorX:             1.0
        relativeSpeedFactorY:             1.0
        relativeSpeedFactorPhi:           1.0
        obstacleAvoidanceScalingFactor:   0.1
        obstacleAvoidanceDistanceFactor:  1.0
    pid:
        X_P:                              0.7
        X_I:                              0.0
        X_D:                              0.0
        Y_P:                              0.7
        Y_I:                              0.0
        Y_D:                              0.0
        XY_P:                             0.7
        XY_I:                             0.0
        XY_D:                             0.0
        PHI_P:                            0.5
        PHI_I:                            0.0
        PHI_D:                            0.0
        maxI_XY:                          0.5
        maxI_Phi:                         0.1
    brake_deceleration:                   0.0
    brake_gamma:                          0.0
    tokyoDrift_radius:                    0.2
    tokyoDrift_step_angle:                0.785
    tokyoDrift_facing_target_tol:         0.5

