alwaysLobshot                : False
alwaysStraightshot           : True
shotStrengthScaling          : 1.0
shotAngleScaling             : 0.7
lobAngleScaling              : 0.5
passScaling                  : 1.0
minLobDistance               : 6.0
maxLobDistance               : 9.0
