ShootPlanningNode: {
  alwaysLobshot                : True,
  disableBHBeforeShot          : True,
  calibrationMode              : False,
  setHeightDelay               : 0.25,
  disableBHDelay               : 0.22,
  lobshotScaling               : 0.9,
  min_lob_distance             : 4.0,
  max_lob_distance             : 12.0,
  max_shot_power               : 180.0,
  max_lever_angle              : 180.0,
  ls_pwr10m                    : 180.0,
  ls_pwr9m                     : 180.0,
  ls_pwr8m                     : 170.0,
  ls_pwr7m                     : 140.0,
  ls_pwr6m                     : 117.0,
  ls_pwr5m                     : 100.0,
  ls_pwr4m                     : 87.0,
  ls_c1                        : 0.20833,
  ls_c2                        : -7.5492,
  ls_c3                        : 106.09,
  ls_c4                        : -722.21,
  ls_c5                        : 2402.1,
  ls_c6                        : -3048.6,
  }
rosdistro: 'groovy'
roslaunch:
  uris: {host_localhost__52278: 'http://localhost:52278/', host_localhost__32819: 'http://localhost:32819/'}
rosversion: '1.9.55'
run_id: d837e3c8-6813-11e4-acf7-00197e8a14ee
