alwaysLobshot                : False
alwaysStraightshot           : False
shotStrengthScaling          : 1.0
shotAngleScaling             : 0.7
lobAngleScaling              : 0.5
passScaling                  : 1.6 # simulation specific
minLobDistance               : 5.5
maxLobDistance               : 8.0
