ShootPlanningNode: {
  alwaysLobshot                : False,
  alwaysStraightshot           : True,
  shotStrengthScaling          : 1.0,
  shotAngleScaling             : 0.7,
  lobAngleScaling              : 0.5,
  passScaling                  : 1.0,
  minLobDistance               : 6.0,
  maxLobDistance               : 9.0,
  }
rosdistro: 'groovy'
roslaunch:
  uris: {host_localhost__52278: 'http://localhost:52278/', host_localhost__32819: 'http://localhost:32819/'}
rosversion: '1.9.55'
run_id: d837e3c8-6813-11e4-acf7-00197e8a14ee
