teamplay_main/rules: {
  setpieceExecuteTimeout      : 7000,
  penaltyExecuteTimeout       : 15000,
  minKickDistanceKicked       : 1.5,
  minPenaltyDistanceKicked    : 2.0,
  minOwnKickoffDistanceKicked : 1.5,
  stimulatePassingEnabled     : true}
rosdistro: 'groovy'
roslaunch:
  uris: {host_localhost__52278: 'http://localhost:52278/', host_localhost__32819: 'http://localhost:32819/'}
rosversion: '1.9.55'
run_id: d837e3c8-6813-11e4-acf7-00197e8a14ee
