teamplay_main/heightmaps: {
  actionDefendAttackingOpponent_hmAvoidBall                                       : 0.0,
  actionDefendAttackingOpponent_hmAvoidObstacles                                  : 0.25,
  actionDefendAttackingOpponent_hmAvoidTeamMates                                  : 0.2,
  actionDefendAttackingOpponent_hmBetweenPoiAndClosestObstacle                    : 0.3,
  actionDefendAttackingOpponent_hmCloseToBallClaimedLocation                      : 0.0,
  actionDefendAttackingOpponent_hmCloseToOwnPos                                   : 0.0,
  actionDefendAttackingOpponent_hmInFrontOfOppGoal                                : 0.0,
  actionDefendAttackingOpponent_hmNearObstacles                                   : 0.3,
  actionDefendAttackingOpponent_hmNearOwnGoal                                     : 0.4,
  actionDefendAttackingOpponent_hmObstaclesBlockingBall                           : 0.0,
  actionDefendAttackingOpponent_hmObstaclesBlockingOppGoal                        : 0.0,
  actionDefendAttackingOpponent_hmObstaclesBlockingTeammates                      : 0.0,

  actionDribbleForPass_hmAvoidBall                                                : 0.0,
  actionDribbleForPass_hmAvoidObstacles                                           : 0.7,
  actionDribbleForPass_hmAvoidTeamMates                                           : 0.2,
  actionDribbleForPass_hmBetweenPoiAndClosestObstacle                             : 0.0,
  actionDribbleForPass_hmCloseToBallClaimedLocation                               : 0.7,
  actionDribbleForPass_hmCloseToOwnPos                                            : 0.0,
  actionDribbleForPass_hmInFrontOfOppGoal                                         : 0.0,
  actionDribbleForPass_hmNearObstacles                                            : 0.0,
  actionDribbleForPass_hmNearOwnGoal                                              : 0.0,
  actionDribbleForPass_hmObstaclesBlockingBall                                    : 0.0,
  actionDribbleForPass_hmObstaclesBlockingOppGoal                                 : 0.0,
  actionDribbleForPass_hmObstaclesBlockingTeammates                               : 0.7,

  actionDribbleForShot_hmAvoidBall                                                : 0.0,
  actionDribbleForShot_hmAvoidObstacles                                           : 0.7,
  actionDribbleForShot_hmAvoidTeamMates                                           : 0.2,
  actionDribbleForShot_hmBetweenPoiAndClosestObstacle                             : 0.0,
  actionDribbleForShot_hmCloseToBallClaimedLocation                               : 0.7,
  actionDribbleForShot_hmCloseToOwnPos                                            : 0.0,
  actionDribbleForShot_hmInFrontOfOppGoal                                         : 0.7,
  actionDribbleForShot_hmNearObstacles                                            : 0.0,
  actionDribbleForShot_hmNearOwnGoal                                              : 0.0,
  actionDribbleForShot_hmObstaclesBlockingBall                                    : 0.0,
  actionDribbleForShot_hmObstaclesBlockingOppGoal                                 : 0.5,
  actionDribbleForShot_hmObstaclesBlockingTeammates                               : 0.0,

  actionMoveToFreeSpot_hmAvoidBall                                                : 0.0,
  actionMoveToFreeSpot_hmAvoidObstacles                                           : 0.2,
  actionMoveToFreeSpot_hmAvoidTeamMates                                           : 0.2,
  actionMoveToFreeSpot_hmBetweenPoiAndClosestObstacle                             : 0.0,
  actionMoveToFreeSpot_hmCloseToBallClaimedLocation                               : 0.0,
  actionMoveToFreeSpot_hmCloseToOwnPos                                            : 0.2,
  actionMoveToFreeSpot_hmInFrontOfOppGoal                                         : 0.54,
  actionMoveToFreeSpot_hmNearObstacles                                            : 0.0,
  actionMoveToFreeSpot_hmNearOwnGoal                                              : 0.0,
  actionMoveToFreeSpot_hmObstaclesBlockingBall                                    : 0.4,
  actionMoveToFreeSpot_hmObstaclesBlockingOppGoal                                 : 0.2,
  actionMoveToFreeSpot_hmObstaclesBlockingTeammates                               : 0.0,

  actionPositionForOppSetpiece_hmAvoidBall                                        : 0.7,
  actionPositionForOppSetpiece_hmAvoidObstacles                                   : 0.3,
  actionPositionForOppSetpiece_hmAvoidTeamMates                                   : 0.2,
  actionPositionForOppSetpiece_hmBetweenPoiAndClosestObstacle                     : 0.3,
  actionPositionForOppSetpiece_hmCloseToBallClaimedLocation                       : 0.0,
  actionPositionForOppSetpiece_hmCloseToOwnPos                                    : 0.0,
  actionPositionForOppSetpiece_hmInFrontOfOppGoal                                 : 0.0,
  actionPositionForOppSetpiece_hmNearObstacles                                    : 0.6,
  actionPositionForOppSetpiece_hmNearOwnGoal                                      : 0.5,
  actionPositionForOppSetpiece_hmObstaclesBlockingBall                            : 0.0,
  actionPositionForOppSetpiece_hmObstaclesBlockingOppGoal                         : 0.0,
  actionPositionForOppSetpiece_hmObstaclesBlockingTeammates                       : 0.0,

  actionPositionForOwnSetpiece_hmAvoidBall                                        : 0.0,
  actionPositionForOwnSetpiece_hmAvoidObstacles                                   : 0.3,
  actionPositionForOwnSetpiece_hmAvoidTeamMates                                   : 0.2,
  actionPositionForOwnSetpiece_hmBetweenPoiAndClosestObstacle                     : 0.0,
  actionPositionForOwnSetpiece_hmCloseToBallClaimedLocation                       : 0.0,
  actionPositionForOwnSetpiece_hmCloseToOwnPos                                    : 0.0,
  actionPositionForOwnSetpiece_hmInFrontOfOppGoal                                 : 0.7,
  actionPositionForOwnSetpiece_hmNearObstacles                                    : 0.0,
  actionPositionForOwnSetpiece_hmNearOwnGoal                                      : 0.0,
  actionPositionForOwnSetpiece_hmObstaclesBlockingBall                            : 0.5,
  actionPositionForOwnSetpiece_hmObstaclesBlockingOppGoal                         : 0.5,
  actionPositionForOwnSetpiece_hmObstaclesBlockingTeammates                       : 0.0
}

rosdistro: 'groovy'
roslaunch:
  uris: {host_localhost__52278: 'http://localhost:52278/', host_localhost__32819: 'http://localhost:32819/'}
rosversion: '1.9.55'
run_id: d837e3c8-6813-11e4-acf7-00197e8a14ee
