motionTypes:
    NORMAL:
        velocityControllers:
            threshold:                            99.0 # effectively disable long-stroke, SPG is preferred for simulation
            longStroke:
                type:                             VelocitySetpointControllerTypeEnum:LINEAR
                coordinateSystem:                 CoordinateSystemEnum:RCS
            shortStroke:
                type:                             VelocitySetpointControllerTypeEnum:SPG
                coordinateSystem:                 CoordinateSystemEnum:RCS
        limits:
            maxVelX:                          1.0
            maxVelYforward:                   1.0
            maxVelYbackward:                  1.0
            maxVelRz:                         1.0
            maxAccX:                          1.5
            maxAccYforward:                   3.5
            maxAccYbackward:                  3.5
            maxAccRz:                         3.5
            maxDecX:                          4.0
            maxDecY:                          7.0
            maxDecRz:                         7.0
            accThresholdX:                    0.0
            accThresholdY:                    0.0
            accThresholdRz:                   0.0
        setPointGenerator:
            synchronizeRotation:                  false
            weightFactorClosedLoopVel:            0.0  # simulation is perfect, so use open loop
            weightFactorClosedLoopPos:            0.7  
            latencyOffset:                        0.00
            convergenceWorkaround:                true
        pid:
            XY_P:                                 1.6
            XY_I:                                 0.0
            XY_D:                                 0.0
            RZ_P:                                 3.5
            RZ_I:                                 0.0
            RZ_D:                                 0.0
            maxI_XY:                              0.5
            maxI_Rz:                              0.1
            fadeI_XY:                             0.99
            fadeI_Rz:                             0.99
    WITH_BALL:
        limits:
            maxVelX:                          0.5
            maxVelYforward:                   0.5
            maxVelYbackward:                  0.5
            maxVelRz:                         2.0
            maxAccX:                          1.0
            maxAccYforward:                   3.0
            maxAccYbackward:                  1.5
            maxAccRz:                         6.0
    ACCURATE:
        limits:
            maxVelX:                          0.5
            maxVelYforward:                   1.0
            maxVelYbackward:                  1.0
            maxVelRz:                         1.0
            maxAccX:                          0.75
            maxAccYforward:                   1.75
            maxAccYbackward:                  1.75
            maxAccRz:                         1.75
    INTERCEPT:
        limits:
            maxVelX:                          1.0
            maxVelYforward:                   2.0
            maxVelYbackward:                  2.0
            maxVelRz:                         2.0
            maxAccX:                          1.5
            maxAccYforward:                   3.5
            maxAccYbackward:                  3.5
            maxAccRz:                         3.5
    SLOW:
        limits:
            maxVelX:                          0.5
            maxVelYforward:                   1.0
            maxVelYbackward:                  1.0
            maxVelRz:                         1.0
            maxAccX:                          0.75
            maxAccYforward:                   1.75
            maxAccYbackward:                  1.75
            maxAccRz:                         1.75
    SPRINT:
        limits:
            maxVelX:                          1.0
            maxVelYforward:                   2.0
            maxVelYbackward:                  2.0
            maxVelRz:                         2.0
            maxAccX:                          1.5
            maxAccYforward:                   3.5
            maxAccYbackward:                  3.5
            maxAccRz:                         3.5
