nominalFrequency:                         30
motionTypes:
    NORMAL:
        velocityControllers:
            threshold:                            1.0
            longStroke:
                type:                             VelocitySetpointControllerTypeEnum:SPG
                coordinateSystem:                 CoordinateSystemEnum:RCS
            shortStroke:
                type:                             VelocitySetpointControllerTypeEnum:PID
                coordinateSystem:                 CoordinateSystemEnum:FCS
        limits:
            maxVelX:                          2.0 # main movement direction
            maxVelYforward:                   1.0 # slow drive for park
            maxVelYbackward:                  1.0
            maxVelRz:                         1.0
            maxAccX:                          4.5 # aggressive
            maxAccYforward:                   1.5
            maxAccYbackward:                  1.5
            maxAccRz:                         3.0
            maxDecX:                          4.0
            maxDecY:                          7.0
            maxDecRz:                         5.0
            accThresholdX:                    0.0
            accThresholdY:                    0.0
            accThresholdRz:                   0.0
        setPointGenerator:
            synchronizeRotation:                  false
            weightFactorClosedLoop:               0.0
            latencyOffset:                        0.0
            convergenceWorkaround:                false
        pid:
            XY_P:                                 3.0
            XY_I:                                 0.01
            XY_D:                                 0.1
            RZ_P:                                 1.0
            RZ_I:                                 0.1
            RZ_D:                                 0.5
            maxI_XY:                              0.5
            maxI_Rz:                              0.1
            fadeI_XY:                             1.00
            fadeI_Rz:                             0.99
    WITH_BALL:
        limits:
            maxVelX:                          0.0 # keeper cannot hold ball
            maxVelYforward:                   0.0
            maxVelYbackward:                  0.0
            maxVelRz:                         0.0
            maxAccX:                          0.0
            maxAccYforward:                   0.0
            maxAccYbackward:                  0.0
            maxAccRz:                         0.0
    ACCURATE:
        limits:
            maxVelX:                          1.0
            maxVelYforward:                   0.5
            maxVelYbackward:                  0.5
            maxVelRz:                         0.5
            maxAccX:                          2.25
            maxAccYforward:                   0.75
            maxAccYbackward:                  0.75
            maxAccRz:                         1.5
    INTERCEPT:
        limits:
            maxVelX:                          2.0
            maxVelYforward:                   1.0
            maxVelYbackward:                  1.0
            maxVelRz:                         1.0
            maxAccX:                          4.5
            maxAccYforward:                   1.5
            maxAccYbackward:                  1.5
            maxAccRz:                         3.0
    SLOW:
        limits:
            maxVelX:                          1.0
            maxVelYforward:                   0.5
            maxVelYbackward:                  0.5
            maxVelRz:                         0.5
            maxAccX:                          2.25
            maxAccYforward:                   0.75
            maxAccYbackward:                  0.75
            maxAccRz:                         1.5
    SPRINT:
        limits:
            maxVelX:                          2.0
            maxVelYforward:                   1.0
            maxVelYbackward:                  1.0
            maxVelRz:                         1.0
            maxAccX:                          4.5
            maxAccYforward:                   1.5
            maxAccYbackward:                  1.5
            maxAccRz:                         3.0
