vision: {
  ROS_rotate_camera: False,
  Minimum_Location_age: 3.0,
  Line_Hue_Center: 89,
  Line_Hue_Delta: 179,
  Line_Saturation_Max: 75,
  Line_Saturation_Min: 0,
  Line_Value_Max: 255,
  Line_Value_Min: 105,
  Ball_Hue_Center: 30,
  Ball_Hue_Delta: 25,
  Ball_Saturation_Max: 255, 
  Ball_Saturation_Min: 135,
  Ball_Value_Max: 255,
  Ball_Value_Min: 100,
  Obstacle_Hue_Center: 89,
  Obstacle_Hue_Delta: 180,
  Obstacle_Saturation_Min: 0,
  Obstacle_Saturation_Max: 227,
  Obstacle_Value_Min: 0,
  Obstacle_Value_Max: 45}
rosdistro: 'groovy

  '
roslaunch:
  uris: {host_localhost__52278: 'http://localhost:52278/', host_localhost__32819: 'http://localhost:32819/'}
rosversion: '1.9.55

  '
run_id: d837e3c8-6813-11e4-acf7-00197e8a14ee
