WorldModelSync: {
  multicastAddress        : "224.16.32.76",
  multicastPort           : 8001,
  allowLoop               : True,
  multicastHop            : 0,
  groupID                 : 2}
rosdistro: 'groovy

  '
roslaunch:
  uris: {host_localhost__52278: 'http://localhost:52278/', host_localhost__32819: 'http://localhost:32819/'}
rosversion: '1.9.55

  '
run_id: d837e3c8-6813-11e4-acf7-00197e8a14ee
