#!/bin/bash -e

mkdir -p build
# qmake should be in yout path, e.g. 
# PATH=$PATH:/opt/Qt5.14.2/5.14.2/gcc_64/bin/

qmake -o build/Makefile jsonReceiver.pro

cd build
make -j 8
cd ../

# ./build/jsonReceiver -h
# ./build/jsonReceiver -r 4 -c
# genius f100 usb webcam calibration file is robot 10
# ./build/jsonReceiver -r 10
./build/jsonReceiver -r 4

