#!/bin/bash
# Falcons wrapper around comm

# comm expects an agent environment variable, so we map our own
export AGENT=${TURTLE5K_ROBOTNUMBER}

# no further arguments -- these are handled via configuration XML
$FALCONS_CODE_PATH/build/packages/facilities/rtdb/comm/comm
