#!/bin/bash
#
# Create a new logging directory and register it.
# 
# JFEI 2015-11-12 creation
# 


logdir="/var/tmp/falcons_control_"`date '+%Y%m%d_%H%M%S'`
# workaround in case fmake --test is called consecutively within one second
while [ -d $logdir ]; do
    sleep 2
    logdir="/var/tmp/falcons_control_"`date '+%Y%m%d_%H%M%S'`
done
mkdir $logdir

