#!/bin/bash

# fixmakefiles 
# Author: Michel Koenen
# Date  : Jan 24, 2015

# Purpose: for some reason, sometimes the standard ROS Makefile is overwritten by a generated Makefile
#          This script will find all those Makefiles and will restore them to the Original ROS Makefile

# Usage  : Call this script without any arguments, the script will call itself with needed
#          arguments to FIX ...

if [ "$1" == "FIXCHECK" ]
then
   #CHECK and FIX the Makefile as delivered by the find

   DIR=`dirname $2`

   #Only check/fix Makefiles found in directory where also a manifest.xml is found!      
   if [ -f $DIR/manifest.xml ]
   then
      #CHECK if Makefile is created by ROS, others we dont want to touch!
      if grep ROSBUILD $2  1>/dev/null  
      then
         # need fix, restore from HEAD
         echo "Fixing $2"
	 git checkout -- $2
      else
         :  # dont need fix
      fi
   fi
else
   find ${TURTLEROOT} -name Makefile -not -path "*/build/*" -not -path "*/gtest/*" -exec $0 FIXCHECK {} \;
fi





