#!/bin/bash
#
# As healthcheck but 'errors only': only display errors; no colored formatting. 
# This is meant for diagnostics channel.
# 
#
# JFEI 20150718 building upon work from MKOE in healthcheck
# JFEI 20150727 disable for simulation

#
# 


# checks do not apply to simulation use case
if [ "$SIMULATED" = "1" ]; then
    exit 0
fi


RESULTSTR=""
LOGDIR=`newest_logdir.py`

DISKUSAGE=`df | grep '/dev/sda1' | nawk '{print $5}' | sed 's/%//'`
if [ "$DISKUSAGE" -gt "85" ]; then
    RESULTSTR=`printf 'disk%d' $DISKUSAGE`" $RESULTSTR"
fi

VOLTAGE=`get_battery_voltage | sed 's/\..*//'`
if [ ! -z "$VOLTAGE" ]; then
    if [ $VOLTAGE -lt "24" ]; then 
        RESULTSTR="lowpower $RESULTSTR"
    fi
fi

if [ ! -c /dev/ttyUSB0 ]; then
    RESULTSTR="nocompass $RESULTSTR"
fi

for sid in `seq 4 9`; do
    ttytype=`dmesg | grep ttyS$sid | awk '{print $NF}'`
    if [ "$ttytype" != "16550A" ]; then
        RESULTSTR="badserial $RESULTSTR"
        break
    fi
done

serialbusy=`grep -i errno $LOGDIR/*.std* | sed 's/.*busy: //' 2>/dev/null`
if [ ! -z "$serialbusy" ]; then
    RESULTSTR="serialbusy $RESULTSTR"
fi

m4logload=`top -b -n 1 | grep m4log | awk '{print $9}' | sed 's/\..*//'`
if [ ! -z "$m4logload" ]; then
    if [ "$m4logload" -gt "40" ]; then
        RESULTSTR="m4wild $RESULTSTR"
    fi
fi

echo $RESULTSTR




