#!/bin/bash

# Andre Pool, March 2017
# Script to write image file to disk

set -e

# assume the disk to which we want to write the disk image is /dev/sdd

sudo gdisk -l /dev/sdd

echo "#### are you sure this is the correct disk ? ####"
echo "wait 10 seconds before continue"

# to prevent destroying accidentally the wrong disc, the script has default been disabled
exit 1

ls -ltr /tmp/ssd_image_1.img.gz

sleep 10

echo "umount partitions (if any)"

sudo umount /dev/sdd1 2>/dev/null || true
sudo umount /dev/sdd2 2>/dev/null || true
sudo umount /dev/sdd3 2>/dev/null || true
sudo umount /dev/sdd4 2>/dev/null || true
sudo umount /dev/sdd5 2>/dev/null || true
sudo umount /dev/sdd6 2>/dev/null || true

echo "begin with transfering data, make take a while"

gunzip --stdout /tmp/ssd_image_1.img.gz | pv -tpreb | sudo dd  of=/dev/sdd bs=4K conv=notrunc,noerror,sync

# repair header at end of disk
sudo sgdisk --move-second-header /dev/sdd

sudo gdisk -l /dev/sdd

echo "all done"

# below some output examples

# -rw-rw-r-- 1 andre andre 4988371051 jul  1 10:23 /tmp/ssd_image_1.img.gz
#  111GB 0:14:21 [ 132MB/s] [                                                                               <=>                         ]
# 29098240+0 records in
# 29098240+0 records out
# 119186391040 bytes (119 GB) copied, 868,04 s, 137 MB/s

# Found valid GPT with protective MBR; using GPT.
# Disk /dev/sdd: 242255664 sectors, 115.5 GiB
# Logical sector size: 512 bytes
# Disk identifier (GUID): C8EBA2BC-A65C-4A43-AFFD-8DE0682F7406
# Partition table holds up to 128 entries
# First usable sector is 34, last usable sector is 242255630
# Partitions will be aligned on 2048-sector boundaries
# Total free space is 9471725 sectors (4.5 GiB)

# Number  Start (sector)    End (sector)  Size       Code  Name
#    1            2048        41945087   20.0 GiB    8300  
#    2        41945088        75499519   16.0 GiB    8200  
#    3        75499520       232785919   75.0 GiB    8300  

# -rw-rw-r-- 1 andre andre 5079271425 jun 19 21:15 /tmp/ssd_image_1.img.gz
# umount partitions (if any)
# begin with transfering data, make take a while
#  100GB 0:13:10 [ 129MB/s] [                <=>                                                                          ]
# 26214400+0 records in
# 26214400+0 records out
# 107374182400 bytes (107 GB) copied, 795,741 s, 135 MB/s


# -rw-rw-r-- 1 andre andre 5079271425 jun 19 21:15 /tmp/ssd_image_1.img.gz
# umount partitions (if any)
# begin with transfering data, make take a while
# 5+3214693 records in
# 5+3214693 records out
# 107374182400 bytes (107 GB) copied, 795,588 s, 135 MB/s


# ****************************************************************************
# Caution: Found protective or hybrid MBR and corrupt GPT. Using GPT, but disk
# verification and recovery are STRONGLY recommended.
# ****************************************************************************
# Disk /dev/sdd: 234441648 sectors, 111.8 GiB
# Logical sector size: 512 bytes
# Disk identifier (GUID): C8EBA2BC-A65C-4A43-AFFD-8DE0682F7406
# Partition table holds up to 128 entries
# First usable sector is 34, last usable sector is 242255630
# Partitions will be aligned on 2048-sector boundaries

# -rw-rw-r-- 1 andre andre 5085526532 jun 19 17:43 /tmp/ssd_image_1.img.gz
# umount partitions (if any)
# begin with transfering data, make take a while
# 6+3410029 records in
# 6+3410029 records out
# 113816633344 bytes (114 GB) copied, 825,784 s, 138 MB/s


# -rw-rw-r-- 1 andre andre 5085526532 jun 19 17:43 /tmp/ssd_image_1.img.gz
# umount partitions (if any)
# begin with transfering data, make take a while
# 7+3407781 records in
# 7+3407781 records out
# 113816633344 bytes (114 GB) copied, 842,102 s, 135 MB/s

# begin with transfering data, make take a while
# dd: error writing ?/dev/sdd?: No space left on device
# 3+3596363 records in
# 3+3596362 records out
# 120034123776 bytes (120 GB) copied, 887,851 s, 135 MB/s
# 

# andre@tweety:/mnt/data2/tmp2$ gunzip --stdout /tmp/ssd_image_1.img.gz | sudo dd  of=/dev/sdd bs=1M
# 26+3207143 records in
# 26+3207143 records out
# 124034899968 bytes (124 GB) copied, 2656,93 s, 46,7 MB/s

# andre@tweety:~$ sudo gdisk /dev/sdd
# Found valid GPT with protective MBR; using GPT.
# 
# Command (? for help): p
# Disk /dev/sdd: 242255664 sectors, 115.5 GiB
# Logical sector size: 512 bytes
# Disk identifier (GUID): C8EBA2BC-A65C-4A43-AFFD-8DE0682F7406
# Partition table holds up to 128 entries
# First usable sector is 34, last usable sector is 242255630
# Partitions will be aligned on 2048-sector boundaries
# Total free space is 3821 sectors (1.9 MiB)
# 
# Number  Start (sector)    End (sector)  Size       Code  Name
#    1            2048        39063551   18.6 GiB    8300  
#    2        39063552        70313983   14.9 GiB    8200  
#    3        70313984       242253823   82.0 GiB    8300  
# 
# Command (? for help): 

# andre@tweety:~/.ssh$ sudo gdisk /dev/sdd
# GPT fdisk (gdisk) version 0.8.8

# Partition table scan:
#   MBR: protective
#   BSD: not present
#   APM: not present
#   GPT: present

# Found valid GPT with protective MBR; using GPT.

# Partition number (1-3): 1
# Partition GUID code: 0FC63DAF-8483-4772-8E79-3D69D8477DE4 (Linux filesystem)
# Partition unique GUID: DA6E7ECF-F245-4689-A2BC-6EEC47AC2EEC
# First sector: 2048 (at 1024.0 KiB)
# Last sector: 39063551 (at 18.6 GiB)
# Partition size: 39061504 sectors (18.6 GiB)
# Attribute flags: 0000000000000000
# Partition name: ''



# Creating new GPT entries.
# Disk /dev/sdd: 234441648 sectors, 111.8 GiB
# Logical sector size: 512 bytes
# Disk identifier (GUID): AE587216-9F07-4BE2-94BA-E929EFC6BA4C
# Partition table holds up to 128 entries
# First usable sector is 34, last usable sector is 234441614
# Partitions will be aligned on 2048-sector boundaries
# Total free space is 234441581 sectors (111.8 GiB)

