#!/usr/bin/env python3
#
# Find newest RDL file


import os, glob


BASE = '/var/tmp'


def newest_RDL_file():
    output = None
    prevt = 0
    files = glob.glob(BASE + "/*.rdl")
    for f in files:
        t = os.path.getmtime(f)
        if t > prevt:
            output = f # overwrite until newest one is stored
            prevt = t
    return output


if __name__ == '__main__':
    print(newest_RDL_file())

