#!/bin/bash
#
# list of packages
# used in falconsbuild.sh and runtests_unitlevel
# JFEI 2016-01-24


(
cat << EOF
ballHandling
common
pathPlanning
worldModel
networkUDP
rtdb3
sharedTypes
refbox
simulation
shootPlanning
diagnostics
peripheralsInterface
teamplay
multiCam
raspiControl
raspiSync
robotControl
visualizer
velocityControl
EOF
) | sed 's/#.*//' # filter comments, like these ;)

