#!/bin/bash
#
# Clear RTDB file storage.
# 
# JFEI 2018-10-21 


location=/tmp
for folder in rtdb2_playback rtdb2_storage ; do
    if [ -d $location/$folder ]; then
        rm -rf $location/$folder
    fi
done

