#!/usr/bin/env python3
#
# Clear RTDB file storage(s). Typically used at robot/coach/simulation startup.
# 
# JFEI 2018-10-21 

import rtdb2
from pathlib import Path

for rtdb_path in Path("/tmp/").glob("rtdb_*"):
    rtdb_store = rtdb2.RtDB2MultiStore(rtdb_path, readonly=False)
    for item in rtdb_store.getAllRtDBItems():
        for agent_store in rtdb_store.agentStores.values():
            agent_store.wakeWaitingConsumers(item.agent, item.key)
            agent_store.get_and_clear(item.agent, item.key)
