#!/bin/bash
#
# Used for setting the git environment for commits
# 
# LCBD 2018-07-31 creation
# 

LOCK_FILE='/home/robocup/.gitUserLock' 

if [ "$#" -ne 2 ]
then
  echo "Usage: $0 <name> <email>"
  exit 1
fi

git config --global user.name $1
git config --global user.email $2

touch $LOCK_FILE


