#!/bin/bash
#
# Configure as certain robot. Useful after having cloned a disk.
#
# 
# July 2017 -- creation by Jan
# 



# sub functions

function subCheckRobotNum
{
    robotNum=$1
    if [ -z "${robotNum##*[!0-9]*}" ]; then
        echo "ERROR: need robot id (1 .. 6)"
        exit 1
    fi
    if [ $robotNum -lt 1 -o $robotNum -gt 9 ]; then
        echo "ERROR: need robot id (1 .. 6)"
        exit 1
    fi
}

function subCheckSudo
{
    if timeout 2 sudo -n id > /dev/null ; then
        echo "Sudo privileges OK."
    else
        echo "This script requires sudo privileges."
        exit 1
    fi
}

function subSetHostName
{
    echo "writing FALCON-$1 into /etc/hostname"
    sudo echo "FALCON-$1" > /etc/hostname
}

function subConfigureIp
{
    # the following was written ages ago by Mathijs, but not tested yet
    # register by default on MSL_FIELD_A_a
    sudo -E /home/robocup/falcons/code/scripts/setup-wifi A
}

function subAutoboot
{
    mkdir -p /home/robocup/.config/autostart
    cat >/home/robocup/.config/autostart/autoboot.desktop <<EOL
[Desktop Entry]
Type=Application
Exec=/home/robocup/falcons/code/packages/robotControl/scripts/robotOnBoot
Hidden=false
NoDisplay=false
X-GNOME-Autostart-enabled=true
Name[en_US]=falconsControl autoboot
Name=falconsControl autoboot
Comment[en_US]=falconsControl autoboot
Comment=falconsControl autoboot
EOL
}

function subMotorConfig
{
    sudo cp /home/robocup/falcons/code/packages/peripheralsInterface/scripts/ttyUSB.rules /etc/udev/rules.d/
}

# parse input
robotNum=$1
subCheckRobotNum $robotNum
subCheckSudo

# safety: only execute this on a robot
if [ ! onRobot ]; then
    echo This script is intended to be executed on a robot ONLY! Exiting...
    exit 1
fi

# do the work
subSetHostName $robotNum
export TURTLE5K_ROBOTNUMBER=$robotNum # temporary for following scripts; normally done when starting shell 
subConfigureIp $robotNum
subAutoboot
subMotorConfig

# TODO sshkeys + gitconfig - Tim can you help with these two?

# TODO anything else? need to actually try this in Japan to figure it all out...

# done
echo "Done, please reboot."

