#!/bin/bash
#
# Start the refbox application.
# 


set -e

PATH_PROCESSING=~/processing-3.5.3
PATH_REFBOX=${FALCONS_DATA_PATH}/external/refbox2019beta/mslrb2015

# require data repo to be uptodate
if [ ! -d $PATH_REFBOX ]; then
    echo "ERROR: data repo not uptodate"
    exit 1
fi

# require processing to have been installed
if [ ! -d $PATH_PROCESSING ]; then
    echo "ERROR: folder not found: $PATH_PROCESSING"
    echo "run script setupRefbox.sh"
    exit 1
fi

# run (using options as suggested in README.md)
cd $PATH_PROCESSING
./processing-java --sketch=$PATH_REFBOX --output=/tmp/refbox2019 --force --run

