#!/bin/bash
#
# Stimulate worldModel
#
# JFEI 2019Q1


set -e

# check input
rdlInputFile=$1
if [ ! -f $rdlInputFile ]; then
    echo "ERROR: require valid input RDL file"
    exit 1
fi

# consumes the first argument so that any remaining arguments can be forwared
shift

# automatically determine output file by applying '_stim' postfix
rdlOutputFile=`echo $rdlInputFile | sed 's/\.rdl/_stim.rdl/'`
agentId=`echo $rdlInputFile | sed 's/.*_r\(.\)\.rdl/\1/'`
if [ -f $rdlOutputFile ]; then
    rm $rdlOutputFile # containment for an feature/issue that cLogFileWriter opens with r/w, causing possible frame corruption at the end of file
fi

# create a logdir for tracing
createLogdir

# configuration overrule -- it would be nicer if we would do this from WorldModelStimulator constructor (TODO)
configTgt=$FALCONS_CONFIG_PATH/worldModel.yaml
configBak=$configTgt.bak
configSrc=$FALCONS_CONFIG_PATH/worldModelStim.yaml
cp $configTgt $configBak
cp $configSrc $configTgt

echo "agentId=$agentId"
export TURTLE5K_ROBOTNUMBER=$agentId
frun worldModel worldModelStimulator -a $agentId -i $rdlInputFile -o $rdlOutputFile -v 4 "$@"

# revert config
mv $configBak $configTgt

exit 0

