#!/usr/bin/env python
#
# Merge lines from tracing, sort on timestamp.
# Lines may be prepended with trace file, as grep would output.
#
# Example:
#    egrep "possession|along|pwnd" trace* | tracemerge > aap
#
#
# 2015-05-12 JFEI creation
#                 

 
import sys, os




unsortedlines = []
sortedlines = {} # timestamps are string-comparable by design
tstamplength = 26


# parse and store
for line in sys.stdin.readlines():
   line = line.strip()
   # timestamp always begins with yyyy-mm
   # so for the coming years we should be fine
   pos = line.find('201')
   if (pos > -1) and (line[pos+4] == '-'):
      tstamp = line[pos:(pos+tstamplength)]
      sortedlines[tstamp] = line
   else:
      unsortedlines.append(line)


# print result
for line in unsortedlines:
   print line
for tstamp in sorted(sortedlines.keys()):
   print sortedlines[tstamp]

