#!/bin/bash
#
# JFEI 2016-12-19 creation
#
# Utility to inspect battery performance.
# Create a rqt_plot window to show all voltage traces.
# No calculation is done, because the signal is far too noisy for automatic processing.
# So you need to judge by eye, fit a line and calculate yourself.
# 



# settings
bagFile=""
playbackRate=100
combined=0

# option parsing
while getopts "b:r:c" opt; do
    case "$opt" in
    b)  bagFile=$OPTARG
        ;;
    c)  combined=1
        ;;
    r)  playbackRate=$OPTARG
        ;;
    esac
done
shift $((OPTIND-1))


# which robots?
if [ -z "$*" ]; then
    # default all
    robots="r1 r2 r3 r4 r5 r6"
else
    robots=`parse_robots $*`
fi


# construct list of topics and variables to plot
topics=""
variables=""
for robot in $robots ; do
    ns=/teamA/robot${robot:(-1)}
    topics="$topics $ns/g_diag_halmw"
    variables="$variables $ns/g_diag_halmw/voltage"
done


# playback bag file, or use live data if available
if [ ! -z "$bagFile" ]; then
    if echo "$bagFile" | grep -q tgz ; then
        # bagfile is packed ... unpack
        bagFileTgz=$bagFile
        bagFile=/var/tmp/`basename $bagFile | sed 's/.tgz//'`
        if [ ! -f $bagFile ]; then
            echo "unpacking $bagFileTgz to /var/tmp"
            cd /var/tmp
            bagFile=`tar zxvf $bagFileTgz`
        fi
        if [ ! -f $bagFile ]; then
            echo "ERROR: could not find $bagFile"
            exit 1
        fi
    fi
    roscore &
    sleep 5
    rosbag play $bagFile -r $playbackRate --topics $topics & 
else
    # assume coachControl is active, do nothing
    echo "assume coachControl is active"
fi


# spawn rqt_plotter(s)
if [ "$combined" = 1 ]; then
    rqt_plot $variables
else
    for robot in $robots ; do
        ns=/teamA/robot${robot:(-1)}
        echo rqt_plot $ns/g_diag_halmw/voltage
        rqt_plot $ns/g_diag_halmw/voltage &
    done
fi


wait

