#!/bin/bash
#
# JFEI 2016-06-07 creation
#
# On request of Raf: inspect motion diagnostics
# Create several rqt_plot windows based on a matchlog, or live
#
# 



# settings
bagFile=""
playbackRate=10


# option parsing
while getopts "b:r:" opt; do
    case "$opt" in
    b)  bagFile=$OPTARG
        ;;
    r)  playbackRate=$OPTARG
        ;;
    esac
done
shift $((OPTIND-1))


# which robots?
if [ -z "$*" ]; then
    echo "ERROR: no robots specified (r1, r2, ... etc)"
    exit 1
fi
robots=`parse_robots $*`


# playback bag file, or use live data if available
if [ ! -z "$bagFile" ]; then
    roscore &
    topics=""
    for robot in $robots ; do
        ns=/teamA/robot${robot:(-1)}
        topics="$topics $ns/g_diag_pathpl $ns/g_diag_worldmodel $ns/g_diag_halmw $ns/g_diag_vision"
    done
    rosbag play $bagFile -r $playbackRate --topics $topics & 
else
    # assume coachControl is active, do nothing
    echo "assume coachControl is active"
fi


# spawn rqt_plotters
for robot in $robots ; do
    ns=/teamA/robot${robot:(-1)}
    rqt_plot $ns/g_diag_halmw/speed_vphi $ns/g_diag_halmw/feedback_vphi $ns/g_diag_vision/ownpos/phi $ns/g_diag_worldmodel/ownpos/phi &
    rqt_plot $ns/g_diag_halmw/speed_vy $ns/g_diag_halmw/feedback_vy $ns/g_diag_vision/ownpos/y $ns/g_diag_worldmodel/ownpos/y &
    rqt_plot $ns/g_diag_halmw/speed_vx $ns/g_diag_halmw/feedback_vx $ns/g_diag_vision/ownpos/x $ns/g_diag_worldmodel/ownpos/x &
done


wait

