#!/bin/bash
#
# JFEI 2018-06-18 creation
#
# Wrapper around tracePlot to filter on some time range.
# 



filter=1408114
tmpDir=/var/tmp/tracePlot
if [ -d $tmpDir ]; then 
    rm -rf $tmpDir
fi
mkdir $tmpDir
for f in `grep -l $filter ptrace*.txt` ; do
    b=`basename $f`
    grep $filter $f > $tmpDir/$b
done

/home/robocup/falcons/code/tools/diagnostics/tracePlot.py --mode shooting $tmpDir/ptrace*

